import { $app, Lodash as _, Storage, Console, fetch, notification, wait, done, gRPC } from "../index.js";
Console.log(Console.logLevel);
Console.log("Hello, World!");
Console.info("Hello, World!");
Console.error("Hello, World!");
Console.warn("Hello, World!");
Console.debug("Hello, World!");
Console.logLevel = "error";
Console.log(Console.logLevel);
Console.log("Hello, World!");
Console.info("Hello, World!");
Console.error("Hello, World!");
Console.warn("Hello, World!");
Console.debug("Hello, World!");
Console.logLevel = "off";
Console.log(Console.logLevel);
Console.log("Hello, World!");
Console.info("Hello, World!");
Console.error("Hello, World!");
Console.warn("Hello, World!");
Console.debug("Hello, World!");
